set_project("shitnet")
set_version("0.1.0")
set_languages("c++23")
set_toolchains("clang")

add_rules("mode.debug", "mode.release")

set_warnings("all", "extra")
add_cxxflags("-Wpedantic", "-Wconversion", "-Wshadow", { tools = { "gcc", "clang" } })

target("shitnet")
set_kind("static")
add_files("modules/*.cppm", { public = true })
add_files("src/shitnet/*.cppm")
add_files("src/shitnet/*.cpp")
add_includedirs("include", { public = true })
add_headerfiles("include/(shitnet/*.h)")

target("shitnet-tests")
set_kind("binary")
set_default(false)
add_deps("shitnet")
add_files("tests/ethernet.cpp")

target("shitnet-cli")
set_kind("binary")
set_default(false)
add_deps("shitnet")
add_files("cli/framework/diagnostic.cppm", { public = true })
add_files("cli/framework/parser.cppm", { public = true })
add_files("cli/shitnet-arp.cppm", { public = true })
add_files("cli/shitnet-commands.cppm", { public = true })
add_files("cli/main.cpp")

target("cli-parser-tests")
set_kind("binary")
set_default(false)
add_includedirs("include")
add_files("modules/shitnet-match.cppm", { public = true })
add_files("cli/framework/diagnostic.cppm", { public = true })
add_files("cli/framework/parser.cppm", { public = true })
add_files("tests/cli-parser.cpp")
